/*
 * generated by Xtext 2.25.0
 */
package arduinoML.ide;

import arduinoML.MyDSLRuntimeModule;
import arduinoML.MyDSLStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyDSLIdeSetup extends MyDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyDSLRuntimeModule(), new MyDSLIdeModule()));
	}
	
}
