/*
 * generated by Xtext 2.25.0
 */
package alarm.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AlarmUiModule extends AbstractAlarmUiModule {

	public AlarmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
