/**
 * generated by Xtext 2.25.0
 */
package arduinoML.tests;

import com.google.inject.Inject;
import dSL.App;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(MyDSLInjectorProvider.class)
@SuppressWarnings("all")
public class MyDSLParsingTest {
  @Inject
  private ParseHelper<App> parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nno viable alternative at input \'Â\'"
      + "\nmismatched input \'»\'\'\'\' expecting \'}\'"
      + "\nThe method or field Â is undefined");
  }
}
