/*
 * generated by Xtext 2.25.0
 */
package arduinoML.parser.antlr;

import arduinoML.parser.antlr.internal.InternalMyDSLParser;
import arduinoML.services.MyDSLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MyDSLParser extends AbstractAntlrParser {

	@Inject
	private MyDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyDSLParser createParser(XtextTokenStream stream) {
		return new InternalMyDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "App";
	}

	public MyDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
