/*
 * generated by Xtext 2.25.0
 */
package xtext.alarm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import xtext.alarm.AlarmRuntimeModule;
import xtext.alarm.AlarmStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AlarmIdeSetup extends AlarmStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AlarmRuntimeModule(), new AlarmIdeModule()));
	}
	
}
