/*
 * generated by Xtext 2.25.0
 */
package alarm.xtext.ide;

import alarm.xtext.AlarmRuntimeModule;
import alarm.xtext.AlarmStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AlarmIdeSetup extends AlarmStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AlarmRuntimeModule(), new AlarmIdeModule()));
	}
	
}
