/*
 * generated by Xtext 2.25.0
 */
package arduinoML.ui.tests;

import com.google.inject.Injector;
import dsl.mydsl.ui.internal.MydslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("arduinoML.MyDSL");
	}

}
