/*
 * generated by Xtext 2.25.0
 */
package alarm.xtext.ui.tests;

import alarm.xtext.ui.internal.XtextActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class AlarmUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("alarm.xtext.Alarm");
	}

}
