/*
 * generated by Xtext 2.25.0
 */
package xtext.alarm;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AlarmRuntimeModule extends AbstractAlarmRuntimeModule {
}
